title: True blog
author: asama1
email: asama1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  The website is a really god one

# social links
twitter_username: i dont have one # DO NOT include the @ character, or else the build will fail!
github_username:  no # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
g
